import { Global, Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
    ApprovalLog,
    ApprovalRequest,
    BookView,
    Booking,
    BookingLabSample,
    CpkAnalysis,
    GLCode,
    ITAsset,
    ITTicket,
    JobOrder,
    JobOrderLog,
    KnowledgeBook,
    Machine,
    MaintenanceStock,
    Notification,
    NotificationGroup,
    Pool,
    PoolItem,
    Post,
    PrinterDepartment,
    PrinterUsageRecord,
    PrinterUserMapping,
    ProductionReport,
    ProductionReportRow,
    RawMaterialPlan,
    RawMaterialPlanPoolDetail,
    RawMaterialPlanRow,
    RepairLog,
    Role,
    RubberType,
    StockCategory,
    StorageLocation,
    Supplier,
    TicketComment,
    User,
} from '../entities';

@Global()
@Module({
    imports: [
        TypeOrmModule.forRootAsync({
            imports: [ConfigModule],
            inject: [ConfigService],
            useFactory: (configService: ConfigService) => ({
                type: 'postgres',
                url: configService.get<string>('DATABASE_URL'),
                entities: [
                    User,
                    Role,
                    Notification,
                    NotificationGroup,
                    ApprovalRequest,
                    ApprovalLog,
                    Booking,
                    BookingLabSample,
                    Supplier,
                    RubberType,
                    Pool,
                    PoolItem,
                    ITAsset,
                    ITTicket,
                    TicketComment,
                    KnowledgeBook,
                    BookView,
                    JobOrder,
                    JobOrderLog,
                    Machine,
                    RepairLog,
                    MaintenanceStock,
                    GLCode,
                    StockCategory,
                    StorageLocation,
                    Post,
                    PrinterDepartment,
                    PrinterUserMapping,
                    PrinterUsageRecord,
                    RawMaterialPlan,
                    RawMaterialPlanRow,
                    RawMaterialPlanPoolDetail,
                    ProductionReport,
                    ProductionReportRow,
                    CpkAnalysis,
                ],
                synchronize: false,
                logging: configService.get('NODE_ENV') === 'development' ? ['error', 'warn'] : false,
                ssl: configService.get('NODE_ENV') === 'production'
                    ? { rejectUnauthorized: false }
                    : false,
            }),
        }),
    ],
    exports: [TypeOrmModule],
})
export class DatabaseModule { }
